{% set name = "ctaplot" %}
{% set version = "0.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ctaplot-{{ version }}.tar.gz
  sha256: 72f99bc06460e5664149c027514a46814b753b303d6731117eaf1c3b516efbc4

build:
  entry_points:
    - gammaboard = ctaplot.gammaboard:open_dashboard
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
  run:
    - python >=3.9
    - numpy >1.16
    - matplotlib-base >=3.6
    - scipy >=0.19
    - astropy-base
    - pytables
    - pandas
    - scikit-learn
    - jupyter
    - ipywidgets
    - pyyaml
    - ipympl
    - tqdm

test:
  imports:
    - ctaplot
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cta-observatory/ctaplot
  summary: Compute and plot CTA IRFs
  description: |
    low-level reconstruction quality-checks metrics computation and vizualisation 
    for Imaging Atmospheric Cherenkov Telescopes such as CTA
  license: MIT
  license_file: license.rst
  doc_url: https://ctaplot.readthedocs.io/
  dev_url: https://github.com/cta-observatory/ctaplot/

extra:
  recipe-maintainers:
    - vuillaut
